version: "3"
services:
  nginx:
    image: meghabt/multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
  server:
    image: meghabt/multi-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client:
    image: meghabt/multi-client
    mem_limit: 128m
    hostname: client
    environment:
      - WDS_SOCKET_PORT=0
  worker:
    image: meghabt/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
